language: c

env:
    - SMVERSION=1.6
    - SMVERSION=1.7
    - SMVERSION=1.8
    - SMVERSION=1.9

matrix:
    fast_finish: true
    allow_failures:
    - env: SMVERSION=1.7
    - env: SMVERSION=1.8
    - env: SMVERSION=1.9

before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib
    - sudo apt-get install lib32stdc++6

before_script:
    - 'if [ $SMVERSION = "1.6" ]; then
          wget -q "http://www.sourcemod.net/smdrop/1.6/sourcemod-1.6.4-git4624-linux.tar.gz" -O sourcemod.tar.gz;
      else
          wget -q "http://www.sourcemod.net/latest.php?version=$SMVERSION&os=linux" -O sourcemod.tar.gz;
      fi'	
    - tar -xzf sourcemod.tar.gz
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - chmod +x compile.sh

script: 
    - ./compile.sh gamecms_services_loader.sp